### ISSUE TITLE
admin rights for dsl seed

### ISSUE THREAD

**Issue by zetan503** [mibexsoftware/bamboo-plan-dsl-plugin#23]
Hi, We want to use your Bamboo DSL, however it seems that only administrators can configure the Seed task. Even though the user has admin rights over the plan they still get this error. Is there a way around giving admin rights to anyone wanting to use the Bamboo DSL?

Users get "Current user must have admin rights to configure this task."

**Comment by mrueegg** [comment]
Hi,

Thanks for your feedback. The problem is that you can mutate every plan and deployment project on the Bamboo instance with a DSL, therefore we decided to demand system admin rights. We could probably restrict this to "restricted admin" permissions, but even then you could do more than "restricted admin's" (e.g., creating new server capabilities which only system admin's can).

If there would be project permissions, we could allow a project admin to generate plans with the DSL if they are only part of that project by analyzing the DSL for plan mutations, but unfortunately, there are no project permissions in Bamboo AFAIK.

This is why we decided to only allow Bamboo system admin's to use seed tasks. What do you think, does that sound reasonable?

**Comment by hsmade** [comment]
On the Seed task, we give the user to run as. Would this not restrict it enough? Maybe, you could restrict this instead. So if you're an admin, you can put anyone, else you can only put your own user. Putting your own user would/should only allow the things to be setup that the user has right to, right?

**Comment by mrueegg** [comment]
I think that's a very good idea, thanks! We will consider this for the upcoming release of the plug-in.

**Comment by mrueegg** [comment]
We implemented this according to your idea and shipped it with version 1.6.0. Thanks again!

**Comment by hsmade** [comment]
Cool, thanks!
