### ISSUE TITLE
Setting Miscellaneous for Jobs

### ISSUE THREAD

**Issue by muchino** [mibexsoftware/bamboo-plan-dsl-plugin#32]
Hi Micha 

Do you have an example to set the Miscellaneous configurations for a job?

![image](https://cloud.githubusercontent.com/assets/1260981/26320348/dde8a1d4-3f22-11e7-9f04-855c6e552631.png)

**Comment by mrueegg** [comment]
Hi,

Yes, I have. Please see the following example:

    job(key: 'SIMPLEJOB', name: 'simple job') {
        description "This was a simple job"
        enabled false
    
        miscellaneous {
            cleanWorkingDirectoryAfterEachBuild()
    
            overrideDefaultHangingBuildDetectionCriteria {
                buildTimeMultiplier 2.5
                logQuietTimeInMinutes 10
                buildQueueTimeoutInMinutes 60
            }
    
            nCoverOutputWillBeProduced {
                nCoverXmlDirectory 'a/b/c'
            }
    
            cloverCodeCoverage {
                automaticallyIntegrateCloverIntoBuild(cloverLicense: 'LICENSE') {
                    generateCloverHistoricalReport()
                    generateJSONReport()
                }
            }
    
            patternMatchLabelling {
                regexPattern '[a-z]+'
                labels 'test'
            }
        }
    }

By the way, we will provide a searchable DSL library documentation with many examples very soon. Stay tuned :-)

**Comment by muchino** [comment]
Perfect - I'll love it. 

Our script is no reading our Bitbucket Server - retrieving all repos and creates for everyone a plan, samne names, keys... so cool !

**Comment by muchino** [comment]
But it's right that this is deprecated?

Plan DSL: warning: (script:88): miscellaneous is deprecated

**Comment by mrueegg** [comment]
Yes, we deprecated `miscellaneous` on jobs because the Groovy IntelliJ plug-in confuses it with the `miscellaneous` function on the plan level. When I Ctrl+clicked on `miscellaneous` in the job it always led me to the one in the plan class. Furthermore, all the properties of the `miscellaneous` block in the job were underlined as unknown because the plug-in assumed these are the settings for the plan.

Did that also happen to you?

The way to go is to use the `misc` block instead. This is kind of unsatisfactory, but I don't believe that this is going to be fixed very soon in the Groovy IntelliJ plug-in.

Could you please explain what you mean by "it doesn't create the plan"? Did you get an error?

**Comment by mrueegg** [comment]
Internal reference: https://youtrack.jetbrains.com/issue/IDEA-173399

**Comment by muchino** [comment]
Thank you for that feedback - the plan's are generated today who knows what I did yesterday :D
