### ISSUE TITLE
artifact definition is not working

### ISSUE THREAD

**Issue by tom999** [mibexsoftware/bamboo-plan-dsl-plugin#5]
I'm trying to define an artifact definition in a job, but get following error:

Plan DSL for Bamboo: failed due to an error in the provided DSL script(s). Details: (buildplan.groovy:43): No signature of method: ch.mibex.bamboo.plandsl.dsl.jobs.Artifacts.defintion() is applicable for argument types: (java.lang.String, java.lang.String, buildplan$_run_closure1$_closure2$_closure4$_closure6$_closure8$_closure13) values: [Products, *.zip, buildplan$_run_closure1$_closure2$_closure4$_closure6$_closure8$_closure13@72936169]Possible solutions: definition(java.lang.String, java.lang.String, groovy.lang.Closure), definition(java.lang.String, groovy.lang.Closure), definition(java.util.Map, groovy.lang.Closure)

Have no idea, whats wrong, because it's like the constructor is defined. thanx for help

[buildplan.groovy.txt](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/files/627278/buildplan.groovy.txt)

**Comment by mrueegg** [comment]
Hi,

Thanks for your feedback. I've seen a typo in your build definition: `defintion` instead of `definition`. Could you please retry and see if this helps?

**Comment by tom999** [comment]
a classic one :-(
thanx works now!

**Comment by mrueegg** [comment]
perfect, I'm glad that it works now (if you are using IntelliJ, typos like this are shown in gray instead of clickable white keywords)

By the way, if you like our add-on, it would be awesome if you could write a short review on our Atlassian Marketplace listing about your experiences: 
https://marketplace.atlassian.com/plugins/ch.mibex.bamboo.plandsl/server/reviews

Thanks in advance
